services:
  - type: web
    name: typerush-web
    env: node
    plan: free
    branch: main
    buildCommand: "npm ci && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
        sync: false
    instances: 1
    regions:
      - oregon
